// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxaZKlsew1fCaTxzlO1k6HMHDl538LbN0',
    appId: '1:896788246930:web:eabcd78e9252e3ef8e514b',
    messagingSenderId: '896788246930',
    projectId: 'otoku-bbd4f',
    authDomain: 'otoku-bbd4f.firebaseapp.com',
    storageBucket: 'otoku-bbd4f.appspot.com',
    measurementId: 'G-DXZ0QEQHGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqIS5RWXiUtBLrw0-og971KvQA8COVHT8',
    appId: '1:896788246930:android:f8c7eb81e28fe7aa8e514b',
    messagingSenderId: '896788246930',
    projectId: 'otoku-bbd4f',
    storageBucket: 'otoku-bbd4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAegRx-ZDdxsWiVDn7CsXlw1ReeVQiGJyo',
    appId: '1:896788246930:ios:1b71aa2080df27188e514b',
    messagingSenderId: '896788246930',
    projectId: 'otoku-bbd4f',
    storageBucket: 'otoku-bbd4f.appspot.com',
    iosBundleId: 'com.example.otoku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAegRx-ZDdxsWiVDn7CsXlw1ReeVQiGJyo',
    appId: '1:896788246930:ios:99d0f3a04da37a628e514b',
    messagingSenderId: '896788246930',
    projectId: 'otoku-bbd4f',
    storageBucket: 'otoku-bbd4f.appspot.com',
    iosBundleId: 'com.example.otoku.RunnerTests',
  );
}
